package br.univel.systemcalcados.Cadastros;

import br.univel.systemcalcados.DAO.ClienteDAO;
import br.univel.systemcalcados.Listagem.ListarCliente;
import br.univel.systemcalcados.Modelos.Cliente;
import javax.swing.JOptionPane;

/**
 *
 * @author WebSystem
 */
public class CadastrarCliente extends javax.swing.JFrame {

    Cliente cliente;

    /**
     * Creates new form CadastrarCliente
     */
    public CadastrarCliente(java.awt.Frame parent, boolean modal) {
        //  super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        txfCodCliente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txfNome = new javax.swing.JTextField();
        txfSobrenome = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txffRG = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        txffCPF = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        txfEndereco = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txfBairro = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txfCidade = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txffCEP = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        txffCelular = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        txffTelefoneRes = new javax.swing.JFormattedTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txfNomeCompletoRefPessoalA = new javax.swing.JTextField();
        txffTelefoneRefPessoalA = new javax.swing.JFormattedTextField();
        jLabel18 = new javax.swing.JLabel();
        txffCelularRefPessoalA = new javax.swing.JFormattedTextField();
        jLabel19 = new javax.swing.JLabel();
        txffNomeCompletoRefPessoalB = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txffTelefoneRefPessoalB = new javax.swing.JFormattedTextField();
        jLabel21 = new javax.swing.JLabel();
        txffCelularRefPessoalB = new javax.swing.JFormattedTextField();
        jLabel22 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel23 = new javax.swing.JLabel();
        txfRefTrabalhoA_NomeEmpresa = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txffRefTrabalhoATelefone = new javax.swing.JFormattedTextField();
        jLabel25 = new javax.swing.JLabel();
        txfTempoServico = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        btnNovo = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();
        txfObservacoes = new javax.swing.JTextField();
        txfEmail = new javax.swing.JTextField();
        txffRendaSalarial = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Cadastrar Clientes");

        jLabel3.setText("CodCliente");

        txfCodCliente.setEditable(false);

        jLabel4.setText("Nome");

        jLabel5.setText("Sobrenome");

        txfSobrenome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfSobrenomeActionPerformed(evt);
            }
        });

        jLabel6.setText("RG");

        try {
            txffRG.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel7.setText("CPF");

        try {
            txffCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel8.setText("Endereço");

        jLabel9.setText("Bairro");

        txfBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfBairroActionPerformed(evt);
            }
        });

        jLabel10.setText("Cidade");

        txfCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfCidadeActionPerformed(evt);
            }
        });

        jLabel11.setText("CEP");

        try {
            txffCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel12.setText("Celular");

        try {
            txffCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel13.setText("Telefone Res.");

        try {
            txffTelefoneRes.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel14.setText("Email");

        jLabel15.setText("Refêrencias Pessoal");

        jLabel16.setText("Nome Completo");

        jLabel17.setText("Telefone");

        try {
            txffTelefoneRefPessoalA.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txffTelefoneRefPessoalA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txffTelefoneRefPessoalAActionPerformed(evt);
            }
        });

        jLabel18.setText("Celular");

        try {
            txffCelularRefPessoalA.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel19.setText("Noome Completo");

        jLabel20.setText("Telefone");

        try {
            txffTelefoneRefPessoalB.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel21.setText("Celular");

        try {
            txffCelularRefPessoalB.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel22.setText("Refêrencias Trabalho");

        jLabel23.setText("NomeEmpresa");

        jLabel24.setText("Telefone");

        try {
            txffRefTrabalhoATelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txffRefTrabalhoATelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txffRefTrabalhoATelefoneActionPerformed(evt);
            }
        });

        jLabel25.setText("Tempo Serviço");

        jLabel26.setText("Renda Salárial");

        jLabel27.setText("Observações");

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnListar.setText("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        try {
            txffRendaSalarial.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("¤ #,##0.00")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txffRendaSalarial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txffRendaSalarialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(txfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txffCEP))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                    .addComponent(txfCodCliente))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txffRG, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txffCPF)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(134, 134, 134)
                                .addComponent(jLabel7)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(txfSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(txffCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txffTelefoneRes))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txfEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(73, 73, 73)
                                        .addComponent(jLabel13)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txfBairro)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel9))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(txfEmail))))))
                .addGap(38, 38, 38))
            .addComponent(jSeparator3)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jSeparator5)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(204, 204, 204)
                                .addComponent(jLabel17))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txfNomeCompletoRefPessoalA, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addComponent(txffTelefoneRefPessoalA, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(txffNomeCompletoRefPessoalB, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txffTelefoneRefPessoalB)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel18)
                            .addComponent(txffCelularRefPessoalA, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                            .addComponent(jLabel21)
                            .addComponent(txffCelularRefPessoalB)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(jLabel15))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(jLabel22))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel27))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txfObservacoes)))
                .addGap(79, 79, 79))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCadastrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnListar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(txfRefTrabalhoA_NomeEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel24))
                            .addComponent(txffRefTrabalhoATelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txfTempoServico, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel26))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txffRendaSalarial, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfCodCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txffRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txffCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txffCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txffCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txffTelefoneRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfNomeCompletoRefPessoalA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txffTelefoneRefPessoalA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txffCelularRefPessoalA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txffNomeCompletoRefPessoalB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txffTelefoneRefPessoalB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txffCelularRefPessoalB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txfRefTrabalhoA_NomeEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txfTempoServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txffRendaSalarial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txffRefTrabalhoATelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addGap(26, 26, 26)))
                .addGap(18, 18, 18)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txfObservacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovo)
                    .addComponent(btnExcluir)
                    .addComponent(btnListar)
                    .addComponent(btnEditar)
                    .addComponent(btnCadastrar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txfSobrenomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfSobrenomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfSobrenomeActionPerformed

    private void txfBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfBairroActionPerformed

    private void txfCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfCidadeActionPerformed

    private void txffRefTrabalhoATelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txffRefTrabalhoATelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txffRefTrabalhoATelefoneActionPerformed

    // btn Cadastrar
    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed

        String nome = txfNome.getText();
        String sobrenome = txfSobrenome.getText();
        String endereco = txfEndereco.getText();
        String bairro = txfBairro.getText();
        String cidade = txfCidade.getText();
        String cpf = txffCPF.getText();
        String rg = txffRG.getText();
        String telres = txffTelefoneRes.getText();
        String telcelular = txffCelular.getText();
        String email = txfEmail.getText();
        String refpessoala_nomecompleto = txfNomeCompletoRefPessoalA.getText();
        String reftrabalhoa_nomeempresa = txfRefTrabalhoA_NomeEmpresa.getText();
        String reftrabalhoa_rendasalarial = txffRendaSalarial.getText();
        String reftraballhoa_temposervico = txfTempoServico.getText();
        String observacao = txfObservacoes.getText();
        String cep = txffCEP.getText();
        String refpessoalb_nomecompleto = txffNomeCompletoRefPessoalB.getText();
        String refpessoaa_telefone = txffTelefoneRefPessoalA.getText();
        String refpessoala_celular = txffCelularRefPessoalA.getText();
        String refpessoalb_telefone = txffTelefoneRefPessoalB.getText();
        String refpessoalb_celular = txffCelularRefPessoalB.getText();
        String reftrabalhoa_telefone = txffRefTrabalhoATelefone.getText();

        try {
            Cliente c1 = new Cliente(nome, sobrenome, endereco, bairro, cidade, cpf, rg, telres, telcelular, email, refpessoala_nomecompleto, reftrabalhoa_nomeempresa, reftrabalhoa_rendasalarial,
                    reftraballhoa_temposervico, observacao, cep, refpessoalb_nomecompleto, refpessoaa_telefone, refpessoala_celular, refpessoalb_telefone, refpessoalb_celular, reftrabalhoa_telefone);

            ClienteDAO dao = new ClienteDAO();

            if (!c1.ValidarCPF(cpf)) {
                JOptionPane.showMessageDialog(null, "Campo CPF em branco ou inválido.");
                txffCPF.requestFocus();
            } else {
                if (c1.validEmail(email)) {
                    JOptionPane.showMessageDialog(null, dao.inserir(c1));

                } else {
                    JOptionPane.showMessageDialog(null, "Campo Email Inválido");
                    txfEmail.requestFocus();
                }
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Verifique se os campos foram digitados corretamente");

        }


    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void txffTelefoneRefPessoalAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txffTelefoneRefPessoalAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txffTelefoneRefPessoalAActionPerformed

    //btn Limpar
    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        limpar();
    }//GEN-LAST:event_btnNovoActionPerformed

    private void txffRendaSalarialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txffRendaSalarialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txffRendaSalarialActionPerformed

    // btn Editar
    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed

        int id = Integer.parseInt(txfCodCliente.getText());
        String nome = txfNome.getText();
        String sobrenome = txfSobrenome.getText();
        String endereco = txfEndereco.getText();
        String bairro = txfBairro.getText();
        String cidade = txfCidade.getText();
        String cpf = txffCPF.getText();
        String rg = txffRG.getText();
        String telres = txffTelefoneRes.getText();
        String telcelular = txffCelular.getText();
        String email = txfEmail.getText();
        String refpessoala_nomecompleto = txfNomeCompletoRefPessoalA.getText();
        String reftrabalhoa_nomeempresa = txfRefTrabalhoA_NomeEmpresa.getText();
        String reftrabalhoa_rendasalarial = txffRendaSalarial.getText();
        String reftraballhoa_temposervico = txfTempoServico.getText();
        String observacao = txfObservacoes.getText();
        String cep = txffCEP.getText();
        String refpessoalb_nomecompleto = txffNomeCompletoRefPessoalB.getText();
        String refpessoaa_telefone = txffTelefoneRefPessoalA.getText();
        String refpessoala_celular = txffCelularRefPessoalA.getText();
        String refpessoalb_telefone = txffTelefoneRefPessoalB.getText();
        String refpessoalb_celular = txffCelularRefPessoalB.getText();
        String reftrabalhoa_telefone = txffRefTrabalhoATelefone.getText();

        Cliente cid = new Cliente(nome, sobrenome, endereco, bairro, cidade, cpf, rg, telres, telcelular, email, refpessoala_nomecompleto, reftrabalhoa_nomeempresa, reftrabalhoa_rendasalarial,
                reftraballhoa_temposervico, observacao, cep, refpessoalb_nomecompleto, refpessoaa_telefone, refpessoala_celular, refpessoalb_telefone, refpessoalb_celular, reftrabalhoa_telefone);

        ClienteDAO dao = new ClienteDAO();

        if (!cid.ValidarCPF(cpf)) {
            JOptionPane.showMessageDialog(null, "Campo CPF em branco ou inválido.");
            txffCPF.requestFocus();
        } else {
            if (cid.validEmail(email)) {
                JOptionPane.showMessageDialog(null, dao.altera(cid, id));
                limpar();
            } else {
                JOptionPane.showMessageDialog(null, "Campo Email Inválido");
                txfEmail.requestFocus();
            }
        }


    }//GEN-LAST:event_btnEditarActionPerformed

    //btn Listar
    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed

        ListarCliente LC = new ListarCliente(this, true);
        LC.setVisible(true);

    }//GEN-LAST:event_btnListarActionPerformed

    // btn Excluir
    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed

        ClienteDAO dao = new ClienteDAO();
        try {
            int op = JOptionPane.showConfirmDialog(null, "Deseja Remover " + txfNome.getText() + txfSobrenome.getText() + "?" + "?");

            if (op == JOptionPane.YES_OPTION) {
                JOptionPane.showMessageDialog(null, dao.Excluir(Integer.parseInt(txfCodCliente.getText())));
                limpar();
            }
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(null, "Selecione um cliente na lista");
        }


    }//GEN-LAST:event_btnExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CadastrarCliente dialog = new CadastrarCliente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField txfBairro;
    private javax.swing.JTextField txfCidade;
    private javax.swing.JTextField txfCodCliente;
    private javax.swing.JTextField txfEmail;
    private javax.swing.JTextField txfEndereco;
    private javax.swing.JTextField txfNome;
    private javax.swing.JTextField txfNomeCompletoRefPessoalA;
    private javax.swing.JTextField txfObservacoes;
    private javax.swing.JTextField txfRefTrabalhoA_NomeEmpresa;
    private javax.swing.JTextField txfSobrenome;
    private javax.swing.JTextField txfTempoServico;
    private javax.swing.JFormattedTextField txffCEP;
    private javax.swing.JFormattedTextField txffCPF;
    private javax.swing.JFormattedTextField txffCelular;
    private javax.swing.JFormattedTextField txffCelularRefPessoalA;
    private javax.swing.JFormattedTextField txffCelularRefPessoalB;
    private javax.swing.JTextField txffNomeCompletoRefPessoalB;
    private javax.swing.JFormattedTextField txffRG;
    private javax.swing.JFormattedTextField txffRefTrabalhoATelefone;
    private javax.swing.JFormattedTextField txffRendaSalarial;
    private javax.swing.JFormattedTextField txffTelefoneRefPessoalA;
    private javax.swing.JFormattedTextField txffTelefoneRefPessoalB;
    private javax.swing.JFormattedTextField txffTelefoneRes;
    // End of variables declaration//GEN-END:variables

    private void limpar() {

        txfNome.setText("");
        txfSobrenome.setText("");
        txfEndereco.setText("");
        txfBairro.setText("");
        txfCidade.setText("");
        txffCPF.setText("");
        txffRG.setText("");
        txffTelefoneRes.setText("");
        txffCelular.setText("");
        txfEmail.setText("");
        txfNomeCompletoRefPessoalA.setText("");
        txfRefTrabalhoA_NomeEmpresa.setText("");
        txffRendaSalarial.setText("");
        txfTempoServico.setText("");
        txfObservacoes.setText("");
        txffCEP.setText("");
        txffNomeCompletoRefPessoalB.setText("");
        txffTelefoneRefPessoalA.setText("");
        txffCelularRefPessoalA.setText("");
        txffTelefoneRefPessoalB.setText("");
        txffCelularRefPessoalB.setText("");
        txffRefTrabalhoATelefone.setText("");
    }

    public void loadCliente(Cliente clienteSelected) {
        try {
            cliente = clienteSelected;
            txfCodCliente.setText(Integer.toString(cliente.getId()));

            txfNome.setText(cliente.getNome());
            txfSobrenome.setText(cliente.getSobrenome());
            txfEndereco.setText(cliente.getEndereco());
            txfBairro.setText(cliente.getBairro());
            txfCidade.setText(cliente.getCidade());
            txffCPF.setText(cliente.getCpf());
            txffRG.setText(cliente.getRg());
            txffTelefoneRes.setText(cliente.getTelRes());
            txffCelular.setText(cliente.getTelCelular());
            txfEmail.setText(cliente.getEmail());
            txfNomeCompletoRefPessoalA.setText(cliente.getRefPessoalA_NomeCompleto());
            txfRefTrabalhoA_NomeEmpresa.setText(cliente.getRefTrabalhoA_NomeEmpresa());
            txffRendaSalarial.setText(cliente.getRefTrabalhoA_RendaSalarial());
            txfTempoServico.setText(cliente.getRefTraballhoA_TempoServico());
            txfObservacoes.setText(cliente.getObservacao());
            txffCEP.setText(cliente.getCep());
            txffNomeCompletoRefPessoalB.setText(cliente.getRefPessoalB_NomeCompleto());
            txffTelefoneRefPessoalA.setText(cliente.getRefPessoalA_Telefone());
            txffCelularRefPessoalA.setText(cliente.getRefPessoalA_Celular());
            txffTelefoneRefPessoalB.setText(cliente.getRefPessoalB_Telefone());
            txffCelularRefPessoalB.setText(cliente.getRefPessoalB_Celular());
            txffRefTrabalhoATelefone.setText(cliente.getRefTrabalhoA_Telefone());

        } catch (Exception e) {

        }

    }
}
