
package br.univel.systemcalcados.Listagem;

import br.univel.systemcalcados.Cadastros.CadastrarCondicoesPagamento;
import br.univel.systemcalcados.DAO.CondicoesPagamentoDAO;
import br.univel.systemcalcados.Modelos.CondicoesPagamento;
import br.univel.systemcalcados.Relatorios.CondicoesPagamento.Condicoes_Pagamento_Relatorio;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author WebSystem
 */
public class ListarCondicoesPagamento extends javax.swing.JFrame {

    CadastrarCondicoesPagamento pai;
    ModeloCondicoesPagamento modelo = new ModeloCondicoesPagamento();

    private CondicoesPagamento condicoesPagamento;

    /**
     * Creates new form ListarCliente
     */
    public ListarCondicoesPagamento(java.awt.Frame parent, boolean modal) {
        pai = (CadastrarCondicoesPagamento) parent;
        initComponents();
        this.setLocationRelativeTo(null);
        tbCondicoesPagamento.setModel(modelo);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    public ListarCondicoesPagamento(Object object, boolean b) {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        txfBuscaCondicao = new javax.swing.JTextField();
        btnbuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbCondicoesPagamento = new javax.swing.JTable();
        btnGerarRelatorio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Listar Condiçoes de Pagamento");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Buscar");

        txfBuscaCondicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfBuscaCondicaoActionPerformed(evt);
            }
        });

        btnbuscar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnbuscar.setText("Pesquisar");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });

        tbCondicoesPagamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbCondicoesPagamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbCondicoesPagamentoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbCondicoesPagamento);

        btnGerarRelatorio.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnGerarRelatorio.setText("Gerar Relatório");
        btnGerarRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarRelatorioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txfBuscaCondicao, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnbuscar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(80, 80, 80))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGerarRelatorio)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txfBuscaCondicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGerarRelatorio)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txfBuscaCondicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfBuscaCondicaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfBuscaCondicaoActionPerformed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed

        modelo.buscar(txfBuscaCondicao.getText());
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void tbCondicoesPagamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbCondicoesPagamentoMouseClicked
        
            if(evt.getClickCount() == 2){
             carregaDados(modelo.getCondicoesPagamento(tbCondicoesPagamento.getSelectedRow()));
             pai.loadCondicoesPagamento(getCondicoesPagamentoSelected());
             dispose();
                //this.setVisible(false);
         }

    }//GEN-LAST:event_tbCondicoesPagamentoMouseClicked

    private void btnGerarRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarRelatorioActionPerformed
        
        
     Condicoes_Pagamento_Relatorio cond = new Condicoes_Pagamento_Relatorio();
    }//GEN-LAST:event_btnGerarRelatorioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListarCondicoesPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListarCondicoesPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListarCondicoesPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListarCondicoesPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ListarCondicoesPagamento dialog = new ListarCondicoesPagamento(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGerarRelatorio;
    private javax.swing.JButton btnbuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tbCondicoesPagamento;
    private javax.swing.JTextField txfBuscaCondicao;
    // End of variables declaration//GEN-END:variables

  //  public CondicoesPagamento getCondicoesPagamento() {

        CondicoesPagamentoDAO cl = new CondicoesPagamentoDAO();
    //    return cl.editarTabela(Integer.parseInt(tbCondicoesPagamento.getValueAt(tbCondicoesPagamento.getSelectedRow(), 0).toString()));

//    }

    private void carregaDados(CondicoesPagamento condicoesPagamento) {
        this.condicoesPagamento = condicoesPagamento;
    }

    public CondicoesPagamento getCondicoesPagamentoSelected() {
        return condicoesPagamento;
    }

    class ModeloCondicoesPagamento extends AbstractTableModel {

        private String[] colunas = {"Cod", "Condicao de pgamento",};
        private List<CondicoesPagamento> pagamentos = new ArrayList<>();
        CondicoesPagamentoDAO condicoespagamentosDao = new CondicoesPagamentoDAO();

        public ModeloCondicoesPagamento() {
            popularTabela();
        }

        private List<CondicoesPagamento> popularTabela() {
        //    pagamentos = condicoespagamentosDao.listar();
            fireTableDataChanged();
            return pagamentos;

        }

        @Override
        public int getRowCount() {
            return pagamentos.size();
        }

        @Override
        public int getColumnCount() {
            return 2;
        }

        @Override
        public String getColumnName(int i) {
            return colunas[i];
        }

            public CondicoesPagamento getCondicoesPagamento(int index){
           return pagamentos.get(index);
        }
        @Override
        public Object getValueAt(int i, int i1) {

            CondicoesPagamento pagamento = (CondicoesPagamento) pagamentos.get(i);

            switch (i1) {
                case 0:
                    return pagamento.getId();

                default:
                    return pagamento.getCondicao();

            }

        }

        private void buscar(String texto) {

            CondicoesPagamentoDAO condicoesPagamentoDAO = new CondicoesPagamentoDAO();
            List<CondicoesPagamento> c = new ArrayList<>();
        //    c = condicoespagamentosDao.listar();

            Pattern padrao = Pattern.compile(".*" + texto + ".*", Pattern.CASE_INSENSITIVE); // criou padrao .* e qualquer coisa antes ou depois

            Iterator i = c.iterator();

            while (i.hasNext()) {
                CondicoesPagamento pagamento = (CondicoesPagamento) i.next();
                Matcher pesquisa = padrao.matcher(pagamento.getCondicao()); // vai comparar com o getCondicao

                if (!pesquisa.matches()) { // resultado da pesquisa
                    i.remove();             // se nao combimou remove.
                }
            }

            // se caso dar erro ao retornar os registros na busca
            this.pagamentos = c;
            fireTableDataChanged();
        }
    }

}
